### PR TITLE
40 adding update class so the file updates live

### PR DESCRIPTION
**Pull request by Jefferson-liu**
Edited the file checker methods so each time they require file data the arraylist of accounts will update to include the most recent updated data

### CODE REVIEW

**Review by a-llison-lau — DISMISSED** [review]
nice changes

**Review by Jefferson-liu — COMMENTED** [review]
changed to make the files update properly

**Review by xiaoxinamek — APPROVED** [review]

**Review by ericshi03 — DISMISSED** [review]
Good changes, good error trapping.

**Review by a-llison-lau — APPROVED** [review]

**Review by enfz — APPROVED** [review]
File updating implementation looks good, could possibly make all file checkers of the same interface in the future since they have similar implementations, however they are for different use cases so leaving them as is would  also work

**Review by Andy-Guo-21 — APPROVED** [review]
Looks good to merge. Public methods need javadoc, but otherwise is fine.

**Review by a-llison-lau — APPROVED** [review]

**Review by kimseeum — APPROVED** [review]
Looks good.

**Pull request merged**
