### PR TITLE
2 feature 2 main menu

### PR DESCRIPTION
**Pull request by enfz**
Connection of Main Menu with Login Menu implemented functionally with clean architecture in mind

### CODE REVIEW

**Review by ericshi03 — DISMISSED** [review]
Good changes. Nice implementation of clean architecture and generalizing all of the files.

**Review by Andy-Guo-21 — APPROVED** [review]
Clean architecture looks good. We will need to write tests for the use cases, and javadoc everything, but it's good to merge into main.

**Review by a-llison-lau — DISMISSED** [review]
Good implementation of clean architecture, we can merge it to main

**Review by Jefferson-liu — APPROVED** [review]
Needs javadoc and tests but otherwise works

**Review by a-llison-lau — APPROVED** [review]
nice changes, we can add some javadoc and tests

**Review by Andy-Guo-21 — APPROVED** [review]
Looks good. Merge conflict has been fixed; it is good to be merged into main

**Pull request merged**
