### PR TITLE
49 testing for login menu use cases

### PR DESCRIPTION
**Pull request by enfz**
Test cases for Login Use Case, Register Use Case, and Admin Use Case implemented

### CODE REVIEW

**Review by a-llison-lau — APPROVED** [review]

**Comment by RaykenJ** [comment]
The tests are very thorough and detailed, looks good to go

**Review by Andy-Guo-21 — APPROVED** [review]
Tests look good.

**Review by xiaoxinamek — APPROVED** [review]

**Review by kimseeum — APPROVED** [review]
Test cases look good.

**Review by ericshi03 — APPROVED** [review]
Good test cases. Thanks for marking the unused files as deprecated - I think that's a smart idea that preserves the history of the work.

**Pull request merged**
