### PR TITLE
Added Javadocs in files in login_menu_use_case and register_menu_use_case

### PR DESCRIPTION
**Pull request by a-llison-lau**

### CODE REVIEW

**Review by Jefferson-liu — APPROVED** [review]
Comments look good

**Review by enfz — APPROVED** [review]
Javadoc looks good

**Review by Andy-Guo-21 — APPROVED** [review]
Javadoc looks good!

**Review by ericshi03 — APPROVED** [review]
Javadoc is good. Contains all the meaningful information

**Pull request merged**
