### PR TITLE
8 feature 8a hint system

### PR DESCRIPTION
**Pull request by xiaoxinamek**
added tests and documentation.
Reconstructed some of the logic to make code more clean and efficient.

### CODE REVIEW

**Comment by ericshi03** [comment]
Please solve the merge conflicts

**Comment by Jefferson-liu** [comment]
We changed the packages so these files will need to be added into their respective packages now before they can be merged

**Review by Andy-Guo-21 — COMMENTED** [review]
I changed it from "X" to "10", so that conflict should take the file from main.

**Comment by Andy-Guo-21** [comment]
> I changed it from "X" to "10", so that conflict should take the file from main.

It should just solve the conflict if we revert the change in the card class.

**Review by enfz — COMMENTED** [review]
Please pull from main and merge your files then recommit or package your files accordingly to main (Into the "future_features" package).

**Pull request closed without merging**
