### PR TITLE
game feature 1.0

### PR DESCRIPTION
**Pull request by RaykenJ**
Depends on Card, Deck, GameWindow

### CODE REVIEW

**Comment by Andy-Guo-21** [comment]
@RaykenJ GitHub Classroom seems to be giving errors. From what I can understand, its because there's no Pool class, yet you are referring to Pool in your code.

Here's my solution: Create an Interface called PoolInterface. When I'm done with my pool class, I will implement that interface.

**Comment by Andy-Guo-21** [comment]
> @RaykenJ GitHub Classroom seems to be giving errors. From what I can understand, its because there's no Pool class, yet you are referring to Pool in your code.
> 
> Here's my solution: Create an Interface called PoolInterface. When I'm done with my pool class, I will implement that interface.

Refer to my pull request on the Pool class for an example.

**Review by kimseeum — APPROVED** [review]
Both classes look good, but maybe the Player[] should be a List instead of an array, since the number of people playing might change when people run out of money.

**Comment by enfz** [comment]
Pull Request closed since existence of updated version has come.

**Pull request closed without merging**
