### PR TITLE
8 feature 8a hint system

### PR DESCRIPTION
**Pull request by xiaoxinamek**
added compareTo method  and made getRankAsInt public for Card. so it become sort-able and easier for my part.
the combination checker class takes in 5 cards, it's checks it's combination and will define what the best combination of 5 cards .
(For example, it a set of cards are Straight Flush, it will not say it is Straight or flush, even though their are the component of it.)
the Hint for combination return an int Array, that represent number of outcome for each combination out of all possible outcomes.
Hint for chance provide Double that represent the initial win rate of the starting hand of a player.
Test case and comments will be add in later.

### CODE REVIEW

**Review by enfz — APPROVED** [review]
The logic looks good. Are hints being considered entities? If so consider separating the hint class into parts such as a factory, entity interface, etc to adhere to clean architecture. Also, do all the public methods need to be public? Since it looks like some of them are only being accessed from inside the class itself.

**Comment by xiaoxinamek** [comment]
> The logic looks good. Are hints being considered entities? If so consider separating the hint class into parts such as a factory, entity interface, etc to adhere to clean architecture. Also, do all the public methods need to be public? Since it looks like some of them are only being accessed from inside the class itself.

Yes, the hints is considered to be entities. Good suggestion, I will try to divide it into more clean parts. 
My purpose was to share the method if anyone need it in their part, it seems like it is unnessasary now, going to change them to private later.

**Review by ericshi03 — APPROVED** [review]
Your logic is good, aside from the clean architecture your code is good.

**Review by Jefferson-liu — APPROVED** [review]
I think that its not a bad idea to have the hints be entities. The code looks fine. Please include tests and some docstring for the public methods

**Pull request merged**
